# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazycal < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/y-magavel/lazycal/releases/download/v0.1.0/lazycal_Darwin_arm64.tar.gz"
      sha256 "6d11434f033da460f7ac537804f7db3dd41dc3a396b9f3e3c4773a10ecae5830"

      def install
        bin.install "lazycal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/y-magavel/lazycal/releases/download/v0.1.0/lazycal_Darwin_x86_64.tar.gz"
      sha256 "15855b229e8dbeca26bfff8d0e39a396d09d0720cbb86a8222fa5f00728c40e8"

      def install
        bin.install "lazycal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/y-magavel/lazycal/releases/download/v0.1.0/lazycal_Linux_arm64.tar.gz"
      sha256 "4c2cdddeac8972024099d7e9b125954779a81d5b1a05eab38708e564cf4fdd93"

      def install
        bin.install "lazycal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/y-magavel/lazycal/releases/download/v0.1.0/lazycal_Linux_x86_64.tar.gz"
      sha256 "d0e789d16ce228626f2d887437a0b619deb3254d15c98bf8fc7f2e42f7634b9d"

      def install
        bin.install "lazycal"
      end
    end
  end
end
