# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazycal < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/y-magavel/lazycal/releases/download/v0.1.1/lazycal_Darwin_arm64.tar.gz"
      sha256 "a1034a4b483f8cf9175894001092858ea1251ed6954c3ecec156793e54bac00d"

      def install
        bin.install "lazycal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/y-magavel/lazycal/releases/download/v0.1.1/lazycal_Darwin_x86_64.tar.gz"
      sha256 "f0c239bf14d2e7a0d70e0d513d9ef94f330b312dde3c1793483745dc60aab593"

      def install
        bin.install "lazycal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/y-magavel/lazycal/releases/download/v0.1.1/lazycal_Linux_x86_64.tar.gz"
      sha256 "e7f87cc4936a78c3a6dfa8750c81a25db14548248eebcbc17bc8ed7a0987199f"

      def install
        bin.install "lazycal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/y-magavel/lazycal/releases/download/v0.1.1/lazycal_Linux_arm64.tar.gz"
      sha256 "e99c4e67834f8a9f6963f496c1f134876b50882e35789a2f7d1876f2025c8164"

      def install
        bin.install "lazycal"
      end
    end
  end
end
